### ISSUE TITLE
"Base type not found in assembly" when using new TPSDK for Swagger on Linux/OSX

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.TypeProviders.SDK#166]
We get this error when using the latest TPSDK with Swagger https://github.com/fsprojects/SwaggerProvider/pull/88#issuecomment-339783919

> error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: Error in pass2 for type PetStore, error: One of your modules expects the type 'SwaggerProvider.Internal.ProvidedSwaggerBaseType' to be defined within the module being emitted. keys = [|TdKey ([],,""); TdKey ([],SwaggerProvider,"PetStore");� TdKey (["SwaggerProvider.PetStore"],,"ApiResponse");�

**Comment by dsyme** [comment]
I can at least now repro this using Windows Subsystem for Linux :)

**Comment by dsyme** [comment]
@sergey-tihon This is now fixed, I think you can try yet another update on Swagger on Linux

**Comment by dsyme** [comment]
@sergey-tihon @isaacabraham @Thorium  That closes out all regression issues I know of with the latest SDK - please let me know ASAP if there are more problems to deal with

**Comment by isaacabraham** [comment]
I've not tried the Azure TP on non-windows yet (or built against core yet) but will get around to it soon :-)

**Comment by ReedCopsey** [comment]
@dsyme I'm still having issues with trying to migrate FsXaml - See https://github.com/fsprojects/FsXaml/issues/73#issuecomment-338833437 for specific details. Project was updated to using this more recent push, with behavior unchanged.
